#!/usr/bin/env bash
# This script install Nginx web server

apt-get -y install nginx
ufw enable
ufw allow Nginx HTTP
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
