#!/usr/bin/env bash
# This script creates a custom 404 page

apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sed -i '52i\            error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx restart
