#!/usr/bin/env bash
#This script configures the web server to contain the name of the server

sed -i "52i\		add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default
service nginx restart
