#!/usr/bin/env bash
# This script installs HA proxy on the lb-01 server

apt -y update
apt -y install haproxy

echo "
frontend alx_lb
	bind *:80
	mode http
	default_backend alx_lb_backend

backend alx_lb_backend
	balance roundrobin
	server 145793-web-01 100.26.56.52:80 check
	server 145793-web-02 54.144.44.192:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
