#!/usr/bin/env bash
# This script installs and configure web-01 and web-02

apt -y update
apt-get -y install haproxy

server_config=\
"
frontend  demilade-frontend
	bind *:80
	mode http
	default_backend demilade-backend
backend demilade-backend
	balance roundrobin
	server 145793-web-01 54.172.162.127:80 check
	server 145793-web-02 18.210.16.159:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
