#!/usr/bin/env bash
# This script installs HA proxy on the lb-01 server

apt -y update
apt -y install haproxy
ufw allow haproxy
sed -i "\n" /etc/haproxy/haproxy.cfg
sed -i "frontend alx_lb" /etc/haproxy/haproxy.cfg
sed -i "        bind *:80" /etc/haproxy/haproxy.cfg
sed -i "	mode http" /etc/haproxy/haproxy.cfg
sed -i "	default_backend alx_lb_backend" /etc/haproxy/haproxy.cfg
sed -i "\n" /etc/haproxy/haproxy.cfg
sed -i "backend alx_lb_backend" /etc/haproxy/haproxy.cfg
sed -i "	balance roundrobin" /etc/haproxy/haproxy.cfg
sed -i "	server 145793-web-01 100.26.56.52:80 check" /etc/haproxy/haproxy.cfg
sed -i "        server 145793-web-02 54.144.44.192:80 check" /etc/haproxy/haproxy.cfg
service nginx restart
