#!/usr/bin/env bash
#This script displays number 1..20

i=1
while [[ $i -le 20 ]]
do
	case $((
		(i == 4) * 1 +
		(i == 9) * 2 +
		(i == 17) * 3)) in
		(1) echo "bad luck from China" ;;
		(2) echo "bad luvk from Japan" ;;
		(3) echo "bad luck from Italy" ;;
		(0) echo "Best School" ;;
	esac
	i=$i+1
done
