#!/usr/bin/env bash
#This script check if a file is exist or not
#then checks whether a file is empty or not
#then check whether a file is a regular file or not

if [[ -e school ]]
then
	echo "school file exists"
	if [[ -s school ]]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	if [[ -f school ]]
	then
		echo "school is a regular file"
	else
		:
	fi
else
	echo "school file does not exist"
fi
